language: node_js
node_js:
- '8'
services: mongodb
cache:
  directories:
  - node_modules
sudo: false
install:
- npm install
script:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_8055d3a86d0e_key -iv $encrypted_8055d3a86d0e_iv
  -in hs-key.pem.enc -out ./hs-key.pem -d
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master